name: dbt Snapshot

on:
  workflow_call:
    inputs:
      table:
        required: true
        type: string

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/108686647178/locations/global/workloadIdentityPools/github-fivethirtyeight/providers/github
          service_account: github-fivethirtyeight@matheusccouto.iam.gserviceaccount.com

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - run: pip install -r dbt/requirements.txt

      - run: dbt snapshot --select ${{ inputs.table }}
        working-directory: dbt