name: Soccer Power Index International Matches

on:
  push:
    branches:
      - main
  schedule:
    - cron: 30 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  etl:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: soccer-api/international/spi_matches_intl.csv
      table: spi_matches_intl

  # snapshot:
  #   uses: ./.github/workflows/snapshot.yml
  #   needs: etl
  #   with:
  #     table: spi_matches_intl
