name: Soccer Power Index International Matches

on:
  push:
    branches:
      - main
  schedule:
    - cron: 30 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: soccer-api/club/spi_matches_intl.csv
      table: spi_matches_intl
